### ISSUE TITLE
Different color for every flag

### ISSUE THREAD

**Issue by Errorname** [Zenika/FAQ#101]
Every flag (unanswered, duplicate, ...) should have its own color.

**Comment by gabriel518** [comment]
![image](https://user-images.githubusercontent.com/47325913/52215953-7df5a700-2895-11e9-9bcc-e2d21527e328.png)
Voici en essai en utilisant [palleton.com](http://paletton.com/#uid=75v0u0kqwnAhpv5mar7tKjmBeea), qu'en penses-tu ?

**Comment by hgwood** [comment]
@Errorname Just FYI, @gabriel518 works with me :)

**Comment by hgwood** [comment]
We think the problem with this color scheme is that green looks positive and red or orange look negative.

**Comment by Errorname** [comment]
Hey! Thank you for working on this issue! I also think green is positive and red/orange is negative. Maybe we can have grey or dark blue instead?

**Comment by gabriel518** [comment]
Nous avons finalement décidé que le OUTDATE aurais la couleur #586069, le DUPLICATE la couleur #BC5820, le UNANSWERED la couleur #157B5F et le INCOMPLETE la couleur #AF1E3A
