### ISSUE TITLE
More visible "New question" button on the homepage

### ISSUE THREAD

**Issue by Errorname** [Zenika/FAQ#102]
A few feedbacks said that they didn't noticed the "new question" button (bottom right of the homepage).

**What could we do to improve this ?**
* Bigger button ?
* "Flashier" design ?

**Comment by bpetetot** [comment]
A button in the topbar with an explicit label "Ask a question" as you can see in lot of application.

Like twitter with the button used to "Tweet":
![image](https://user-images.githubusercontent.com/516360/46036857-e3c36c80-c106-11e8-81ef-c0aeddb24ce2.png)

**Comment by Errorname** [comment]
Good idea !
And should the existing button be bigger ? Or should it stays like now ?

**Comment by Errorname** [comment]
This has been implemented by #161
