### ISSUE TITLE
I can't update my own answer

### ISSUE THREAD

**Issue by olivierhuber** [Zenika/FAQ#147]
I click on "edit my answer" and i save and i simply see a loading gif ...

https://faq.zenika.com/q/qu'est-ce-que-la-formation-de-formateur-ou-ttt-(train-the-trainer)-cjqf5l7a60j820809ueb16l5k/answer

**Comment by Errorname** [comment]
Thank you for reporting this issue. This was fixed with #492d9a0d earlier today
