### ISSUE TITLE
Pagination: Go back to top

### ISSUE THREAD

**Issue by nlepage** [Zenika/FAQ#20]
After scrolling down to the bottom of page 1 and clicking page 2 link, the scroll stays at the bottom of page 2.
It doesn't feel right to have to scroll up to see the questions of page 2.

Scroll back to top after clicking a page link ?
Is there any change of pagination system planned in the upcoming interface changes ?

**Comment by Errorname** [comment]
Good enhancement, I'll do that.

There is currently no planned changes in the pagination system logic (except for some css changes coming with the new UI)
