### ISSUE TITLE
Hide "source links form" when creating / editing a response

### ISSUE THREAD

**Issue by bpetetot** [Zenika/FAQ#47]
Adding sources it's an advanced feature not often used, but the default "source form" take a lot of space in edit answer form. I propose to hide it, and just have the "More source" button to add a "source link".

Of course, when editing, if there are already source links, they are displayed.

## before 
<img width="811" alt="screen shot 2018-04-08 at 12 16 36" src="https://user-images.githubusercontent.com/516360/38466317-bec4d2e4-3b27-11e8-9812-2adb15b384c8.png">

## after
<img width="812" alt="screen shot 2018-04-08 at 12 18 42" src="https://user-images.githubusercontent.com/516360/38466320-c4505134-3b27-11e8-9ac7-e0c475a3eaa0.png">

## Changes
- replace the "Sources :" title by a "Add source link" button
- hide the empty "source link" form
- bonus: replace "Edit" button name by "Save answer"

**Comment by Errorname** [comment]
Closed by #51
