### ISSUE TITLE
Add a "report a bug" link

### ISSUE THREAD

**Issue by bpetetot** [Zenika/FAQ#48]
As FAQ app it still in beta and active development, It could be useful to have a quick access to the git repository to quickly report bugs and enhancement.

I have done it in "Conference Hall", and it's very useful : 
<img width="836" alt="screen shot 2018-04-08 at 12 35 49" src="https://user-images.githubusercontent.com/516360/38466467-d6359060-3b29-11e8-8942-0121a04e2340.png">

**Comment by Errorname** [comment]
Actually, there is already a "report a bug" link:
![image](https://user-images.githubusercontent.com/6669733/38484359-a080cef0-3bd6-11e8-81bb-67b37565ce5d.png)
Maybe it isn't at the right place, what do you think ?

**Comment by bpetetot** [comment]
yes I didn't see it, while it's in beta testing, IMO it should be directly visible

**Comment by Errorname** [comment]
Closed by #51
