### ISSUE TITLE
I can reset the words searched in one clic.

### ISSUE THREAD

**Issue by Zenigata** [Zenika/FAQ#49]
I think it is better to add a cross button to erase the search field.

**Comment by Errorname** [comment]
I agree, the search field should have a cross button

**Comment by bpetetot** [comment]
`<input>` with attribute `type="search"` usually (browser dependent) add a cross button : 

![image](https://user-images.githubusercontent.com/516360/38555853-fc7fae50-3cc7-11e8-9a1d-b602b9f9b5b0.png)

It could be enough.

**Comment by Errorname** [comment]
This is what's shown in chrome:
![image](https://user-images.githubusercontent.com/6669733/38556967-c51e7c8a-3ccb-11e8-8e8e-e4f6847d6b3a.png)

But there is no hover effect on the cross

**Comment by Errorname** [comment]
Implementing it ourselves would make it browser independant AND prettier 🙂

**Comment by Errorname** [comment]
Closed by #51
