### ISSUE TITLE
Ease the contributor on-boarding

### ISSUE THREAD

**Issue by hgwood** [Zenika/FAQ#52]
- [ ] document how to bootstrap the project with a GraphCool local cluster (ideally, `npm install` + `npm start` should be enough to run the app locally from scratch)
- [ ] make the app work without Algolia access (disables the search feature)
- [ ] make the app work without Mailgun access (disables the emailing feature)

**Comment by Errorname** [comment]
There is already a PR which does all of this: #44 🙂

**Comment by hgwood** [comment]
Missed it, sorry
