### ISSUE TITLE
I found a question which is flag as double imcomplete

### ISSUE THREAD

**Issue by frinyvonnick** [Zenika/FAQ#60]
id: comment-ouvrir-un-plan-epargne-entreprise-pee-cjfsl7evsalxw01802dl15ou7

![image](https://user-images.githubusercontent.com/13099512/38737608-0b7d7b48-3f30-11e8-85bf-f999f8271aee.png)

**Comment by Errorname** [comment]
Unfortunately, I could not reproduce this bug.
This may have been fixed with optimisticResponse in PR #46

**Comment by Errorname** [comment]
I must apologize, I spoke too quickly; I just reproduced this bug.
Thanks for the issue
