### ISSUE TITLE
the back button in page 404 is not very useful

### ISSUE THREAD

**Issue by bpetetot** [Zenika/FAQ#61]
when you access a page with a bad url through an external link (workplace, slack), you will be redirected to the 404 page not found, but the "Go back" button will not work, because it can't go anywhere.

Instead, you should propose a "Home" button.

![image](https://user-images.githubusercontent.com/516360/38743482-70e957cc-3f3f-11e8-8158-52124a0b28fd.png)

**Comment by Errorname** [comment]
Closed by #63
