### ISSUE TITLE
Why do we need webpack and graphcool as global dependencies ?

### ISSUE THREAD

**Issue by bpetetot** [Zenika/FAQ#65]
I just read the [step by step guide](https://github.com/Zenika/FAQ/blob/master/docs/step_by_step.md#1-global-dependencies), it says, that we need to install webpack and graphcool framework as global dependencies.

But I really dont like to install that kind of deps as global because they evolve quickly and often. And I could have different version on different projects. `docker`, `node` and `npm` should be the only prerequisites.

I think you should add them as `dev-dependencies` in your `package.json`.

Is there any reason to have them as global dependencies ?

**Comment by Errorname** [comment]
I agree with you, they should be added as dev dependencies and not as global dependencies. I will update this now.
