### ISSUE TITLE
Problème de connexion

### ISSUE THREAD

**Issue by louckousse** [Zenika/FAQ#66]
Quand je vais sur le site, régulièrement il ne me connecte pas automatiquement. Voici deux captures d'écran.
![image](https://user-images.githubusercontent.com/6485933/39310166-02f93e82-496a-11e8-9b84-1372e858093b.png)
![image](https://user-images.githubusercontent.com/6485933/39310180-0adcd230-496a-11e8-9347-ba3f1c85d7e6.png)

**Comment by Errorname** [comment]
Thank you for the report, I'll try to reproduce this and fix this soon
