### ISSUE TITLE
Answer editor is not updated

### ISSUE THREAD

**Issue by aceol** [Zenika/FAQ#72]
If I edit an answer the date & author info are not updated

i.e edited question may the 15th [que faire](https://faq.zenika.com/q/que-faire-si-je-ne-recois-pas-lemail-pour-remplir-les-evaluations-a-la-fin-de-ma-formation-cjfwllnuqedw70107kdmcrapz)

**Comment by hgwood** [comment]
See #18. :)

**Comment by hgwood** [comment]
Oh #18 is about questions. Sorry. :)

**Comment by Errorname** [comment]
Thank you for the submitting this issue.

We plan to add an "history log" of changes made to the question or its answer, by whom and when.

Currently, the user associated should be seen as "The first user who answered this question"
