### ISSUE TITLE
improve search efficiency

### ISSUE THREAD

**Issue by bpetetot** [Zenika/FAQ#77]
When I ask that kind of question:
![image](https://user-images.githubusercontent.com/516360/40532652-7515cd3a-6000-11e8-9034-d63d91dd9d15.png)

The real result is at the 19th position over 20 results,  and this question contains most of the searched word in my query, unlike other results contains searched words into their answer.
![image](https://user-images.githubusercontent.com/516360/40532686-926301d2-6000-11e8-9a4c-79d001258201.png)

I think we should work on threshold and weight when on searching between the question and the answser. Question may need to have more weight than results in the response, and we should maybe avoid searching in common words like: "le", "la", "the", "a"...

**Comment by Errorname** [comment]
Some docs:
https://www.algolia.com/doc/api-reference/api-parameters/removeStopWords/

**Comment by Errorname** [comment]
Closed by #87

**Comment by Errorname** [comment]
👌 👌  Thanks again for noticing this !
![image](https://user-images.githubusercontent.com/6669733/42157613-770f4588-7dee-11e8-9a2f-f8506300b73e.png)

**Comment by bpetetot** [comment]
Great 👍
