### ISSUE TITLE
Filter by tags return no results

### ISSUE THREAD

**Issue by nlepage** [Zenika/FAQ#93]
Whatever tag I'm trying, still no results.
Using text search or not doesn't change anything.

![screenshot from 2018-09-24 07-14-01](https://user-images.githubusercontent.com/19571875/45938380-adcc9e00-bfc9-11e8-8e71-5ec4e73dc4a1.png)

**Comment by Errorname** [comment]
Thank you for the notification. I forgot to update Algolia's settings after the manual migration. This should now work.

I am currently working on the Continuous Integration of the new backend. This should have mistakes like this in the future.

Thanks again for the heads up!
