### ISSUE TITLE
Tags filter: Same tag selected several times

### ISSUE THREAD

**Issue by nlepage** [Zenika/FAQ#94]
I don't know what is the expected behavior when clicking on an already selected tag, but 2 options:
 - nothing happens
 - the tag is unselected

![screenshot from 2018-09-24 11-09-29](https://user-images.githubusercontent.com/19571875/45944437-702c3d00-bfea-11e8-991f-27c0ce4e9021.png)

**Comment by nlepage** [comment]
Yep, I also like the second one, even if it's redundant.

**Comment by Errorname** [comment]
This has been fixed and implemented by #95
