### ISSUE TITLE
Error when submitting an answer

### ISSUE THREAD

**Issue by bpetetot** [Zenika/FAQ#96]
When I have submitted an answer, I got the following error:

![image](https://user-images.githubusercontent.com/516360/46014813-dd1a0280-c0d0-11e8-922a-c0e2c23b2a2d.png)

But the answer was correctly saved.

**Comment by Errorname** [comment]
Thank you for submitting the issue.

To help me identify the issue:
* What was the question you were answering ?
* Was there already an answer which you were improving, or was this the first answer ?
